/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "omfqjzwegmiezbfpjysp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZnFqendlZ21pZXpiZnBqeXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNjY2NDcsImV4cCI6MjA4MDg0MjY0N30.YkSoV-8t4qWXNppvM2t1mDsdkirIoNRpMmQUjvVk-3o"